### ISSUE TITLE
Expanding to Memes

### ISSUE THREAD

**Issue by rfsbraz** [sagargp/trollicons#15]
How do you guys feel about expanding trollicons to include most of the internet used memes? Like Paranoid Parrot, Insane Wolf, Success Kid, Socially Awkward Penguin, Foul Bachelor Frog, Lame Pun Coon, What Have I Done, and so on.

**Comment by unregistered** [comment]
I think it goes over the scope of the project, but it's not like we haven't been adding other faces already.

**Comment by sagargp** [comment]
maybe we can just fork another pack just for those

**Comment by rfsbraz** [comment]
A pack just with memes? I know adium supports multiple emoticons packs, but do others IM clients?

**Comment by sagargp** [comment]
others don't, that's a problem. i can just see the trollicons getting way too big. where would it end? there are dozens of advice animals.

**Comment by rfsbraz** [comment]
I'll work on a couple of memes anyway, worst case scenario I'll just give them some use myself.

**Comment by paradox460** [comment]
I personally don't find the advice animals that funny, or relevant to conversations. Most of them are better being linked to instead of included into the IM stream?

**Comment by unregistered** [comment]
I think you should fork it and see how it goes.  Send me a link to your fork once its up and I'll give it a try too.  If it works out well or becomes popular we can see about merging it.

**Comment by sagargp** [comment]
that sounds pretty good... we can see how easily it flows in conversations

**Comment by rfsbraz** [comment]
Added various meme faces, give them a try.

**Comment by paradox460** [comment]
Perhaps we could create a reference image? This wouldn't be too hard to do dynamically, using imagemacgick

**Comment by sagargp** [comment]
what do you mean "reference image"?

**Comment by paradox460** [comment]
A contact sheet made up of all the images in the pack, and their command(s)
On Monday, May 16, 2011 at 6:43 PM, sagargp wrote:
what do you mean "reference image"?

**Comment by sagargp** [comment]
oh yeah, that's a good idea, i'll make an issue

**Comment by paradox460** [comment]
I'll see if I can find the imagemagick script, and if I can't, I'll write it
On May 16, 2011 7:44 PM, "sagargp" <
reply@reply.github.com>
wrote:
