### ISSUE TITLE
Creation of new faces

### ISSUE THREAD

**Issue by unregistered** [sagargp/trollicons#17]
The actual icons- the most important part.

Evilmegusta
"I will kill you in your sleep"
Gaytroll
Satantroll
Are you fucking kidding me
Oh sweet jesus
Aww no / Aww wait..
Bigfrown

**Comment by sagargp** [comment]
let's throw in a "look of disapproval" too... not everyone can support it when it's text based, if they don't have the font

**Comment by unregistered** [comment]
Did the first 4 in 4c7979a305c0082707b4a553631d094ab0ffe621

**Comment by vxq9e7bx** [comment]
where is the famous facepalm?

**Comment by sagargp** [comment]
noted

**Comment by unregistered** [comment]
Fixed with wikichen's commit
