### ISSUE TITLE
ALL THE THINGS!

### ISSUE THREAD

**Issue by tobsn** [sagargp/trollicons#26]
http://knowyourmeme.com/photos/141051-x-all-the-y
http://canv.as/ugc/original/3332f6ef40a0ae9dd34d6d5eaa7e7524656a1f77.png

someone please add them ;)

**Comment by sagargp** [comment]
i've only seen this face in "advice animals" posts or similar, not really in rage comics. we've decided against putting A.A. icons because it'll make the icon pack really big and cluttered.

**Comment by tobsn** [comment]
but it needs ALL THE THINGS! ;)

well... anyway ;)
