### ISSUE TITLE
Ain't workin with Messages.app

### ISSUE THREAD

**Issue by paulmillr** [sagargp/trollicons#32]
Any idea how to make it work with new messenger from Apple? It replaces iChat.

http://www.apple.com/macosx/mountain-lion/messages-beta/

**Comment by unregistered** [comment]
It works partially for me. It seems like the iChat.app directory appears as "Messages.app" in Finder but can still be accessed by the installer. Afterwards, I can get a list of rage faces in the smiley list, but sending them fails.

**Comment by unregistered** [comment]
Messages.app is still in Beta, so we'll postpone this issue for now

**Comment by paulmillr** [comment]
no longer in β, release in five days

**Comment by unregistered** [comment]
Things I've learned:

Messages.app no longer stores the emoticons as tiff files in its applications folder. It stores SmileyTable.plist in `/System/Library/PrivateFrameworks/SocialUI.framework/Versions/A/Resources/en.lproj` and pulls images from the system Emoji font.

Not sure what the best way to get custom icons into Messages is. We could patch the Emoji font, but that would have far reaching effects.

**Comment by paulmillr** [comment]
woah bullshit. that’s sad.

**Comment by sagargp** [comment]
well messages.app supports images. we could just do something along the
lines of the rage faces app for iPhone that just copies PNGs so you can
paste them directly into messages. i know some apps like this already
exist, maybe we can subsume one? or just make our own?

-sagar

**Comment by paulmillr** [comment]
I think this can work but only for iMessage. I tried sending stuff via XMPP, it seem to have many restrictions and doesn’t work.

**Comment by sagargp** [comment]
dang, i forgot about that part of Messages. i guess a patch to emoji is the
best. or a new font.

-sagar

**Comment by paulmillr** [comment]
We will lost interoperability with non-OSX clients in this case, won’t we?

**Comment by sagargp** [comment]
i'm not sure. hopefully Messages doesn't do per-protocol checking. if
that's the case, then [troll] --> some font icon in Messages, and also some
png in other supported clients. if Messages does do checking, then we're
probably screwed.

**Comment by carlosefonseca** [comment]
Hi!
Any update in this front?

**Comment by unregistered** [comment]
Not on our side. The only things that work seem very hackey.
