### ISSUE TITLE
icon shortcuts are too easy to typo

### ISSUE THREAD

**Issue by sagargp** [sagargp/trollicons#9]
for example:

Me: hey bro [friends[
Me: damnit, [friends*
Me: [friends[]***
Me: ![](https://github.com/sagargp/trollicons/raw/master/Icons/Rage/Intense-fu2-rage2.png)

I propose a new system where for each [rage] we also support /rage or something similar. Maybe even [rage and [rage[ are caught too, so we avoid those stupid typos.

**Comment by paradox460** [comment]
Yes, i've been having these irritating typos. So…fucking…irritating.

**Comment by unregistered** [comment]
Fork and patch human nature?

**Comment by paradox460** [comment]
I've figured out a solution, and i'll make a branch with it.

**Comment by unregistered** [comment]
Duplicate of #24
